### ISSUE TITLE
Constantly freezing/desyncing

### ISSUE THREAD

**Issue by scrubbrush** [TES3MP/openmw-tes3mp#424]
When playing tes3mp one of us will suddenly see the other players freeze in place and when we try to type in the text chat it is no longer working. No idea what the cause is but it's happening constantly.

- We're both using the gog version with no plugins etc

- We've both hosted games and the same thing happens in either one

**Comment by davidcernat** [comment]
When you get it to happen, can you take a screenshot of the black window that starts up alongside your client?

**Comment by scrubbrush** [comment]
Here's a pastebin of the log from the other person who crashed recently, I assume this is what you mean:

https://pastebin.com/Y8xsPyDg

**Comment by scrubbrush** [comment]
Somewhere around lines 359 and 374 there's a desync/freeze I believe.

**Comment by davidcernat** [comment]
Actually, no. I don't want the log because it sometimes doesn't record framelistener errors (which is probably what you're getting).

If it really is happening constantly, you can probably take a screenshot of the black window when it happens or right after it has happened.

**Comment by scrubbrush** [comment]
This is a video from my point of view with the server log and console window included. He freezes around 18:00 https://youtu.be/DczEknPftCQ I say crash in the video but I mean freeze/desync

These are the console screenshots from his point of view around the time he gets the freeze:
https://i.imgur.com/yLCrjT6.png (this was we're both in the game)
https://i.imgur.com/N8wlufg.png (I dropped out of the server to go put the vid on youtube he rejoined the server and got the freeze again)

**Comment by scrubbrush** [comment]
Here's another one: https://i.imgur.com/veKiwsY.png

From his screen he is jumping all over the place but on mine he is just frozen: https://i.imgur.com/eH9ukzp.jpg

**Comment by davidcernat** [comment]
Alas, there's really nothing out of the ordinary in the debug messages there.

Can you see what happens when you bring a third player into the mix?

**Comment by scrubbrush** [comment]
We fixed the issue by switching to hamachi, the other person was having very strange connection issues.
