### ISSUE TITLE
Is there a way to build latest tes3mp?

### ISSUE THREAD

**Issue by AcTiViSioN911** [TES3MP/openmw-tes3mp#572]
Hello, im trying to find a way to build tes3mp with latest fixes. I was able to build it on linux using forge+deploy but i cant run it, i can launch openmw and the game, but i get a launch error trying to run server like i did on windows (im not familiar with linux but i followed the guide and everything looks good). And i cant even run prebuilt server on linux, i get access denied error from console and if i just double click it asks about running program, no idea why. I just want to play with latest fixes... sorry for my english)

**Comment by davidcernat** [comment]
Your issue doesn't have anything to do with building tes3mp at all, considering you have trouble running the prebuilt server in the first place.

Please avoid creating issues that don't make sense.
