### ISSUE TITLE
My friend shatters the entire server when he logs in and he's a threat to the world

### ISSUE THREAD

**Issue by Zakaria-ouertani** [TES3MP/openmw-tes3mp#681]
Playing with friends and one of them makes everyone lag /desync and can damage just from the air he punches, he's also invulnerable to damage sometimes

And this happens only and only when _**he**_ enters the server. (he plays an unarmed, unarmored, jacked orc maybe thats relevant)

**Comment by testman42** [comment]
can you tell us more about your server and how does your friend connect to it?
is server running just GOTY Morrowind? Any custom scripts or mods?
Does this happen on other servers as well?
Is your friend a Daedric Prince IRL?

**Comment by Zakaria-ouertani** [comment]
> can you tell us more about your server and how does your friend connect to it? is server running just GOTY Morrowind? Any custom scripts or mods? Does this happen on other servers as well? Is your friend a Daedric Prince IRL?


It's goty morrowind with a "few" mods([content list from cfg](https://pastebin.com/yyUyEjAD))([nexus links](https://pastebin.com/1ETwQHvp)) and [scripts](https://pastebin.com/EmK40b3h)
though this problem occured before we added any scripts or mod
We've tried [hamachi](https://vpn.net/) and [zerotier](https://www.zerotier.com/) and always the same problem.
Using tes3Mp [0.8.1](https://github.com/TES3MP/TES3MP/releases/tag/tes3mp-0.8.1)

More detail on what happens when he logs in
Sometimes he logs in and can play fine and sometimes it starts as soon as he logs in
He becomes unable to send messages and only interact with npcs, sees every action we do after a big delay and can damage us when we're away from him when he punches nothing as if we were in front of him.
When we were able to put down this menace his corpse was still standing, still takes damage and stays there without respawning.
After that happened he unleashed 10% of his power and became called "Unlogged Player(number here)" and crashed the server.
More recently, he instantly becomes called unlogged player and instantly gets unlogged and no one can log in after him

Will Dagoth Ur be safe if this guy ever becomes able to play normally ?

**Comment by Zakaria-ouertani** [comment]
![image](https://github.com/TES3MP/TES3MP/assets/75418838/790802ef-28aa-4baf-9a09-1de6208afccc)
Today he got slightly mad and crashed the server with a single punch while naked
after we were kicked he stayed on the server a bit and decided its not worth it so he kicked the server

**Comment by magicaldave** [comment]
Post the server logs and preferably also his client logs. On Windows, both can be found in Documents/My Games/openmw. 

It sounds like he has an extremely poor connection to whomever is hosting. Try using /list ingame to check his ping. 

You might resolve this by switching hosts or simply not hosting out of your house. Also try other servers and see if the same happens.

**Comment by Zakaria-ouertani** [comment]
> Post the server logs and preferably also his client logs. On Windows, both can be found in Documents/My Games/openmw.
> 
> It sounds like he has an extremely poor connection to whomever is hosting. Try using /list ingame to check his ping.
> 
> You might resolve this by switching hosts or simply not hosting out of your house. Also try other servers and see if the same happens.


Server Log: [tes3mp-server-2024-03-02-22_28_45.log](https://github.com/TES3MP/TES3MP/files/14473767/tes3mp-server-2024-03-02-22_28_45.log)
Client Log: [tes3mp-client-2024-03-02-10_45_02.log](https://github.com/TES3MP/TES3MP/files/14473768/tes3mp-client-2024-03-02-10_45_02.log)

**Comment by Zakaria-ouertani** [comment]
I'll also try letting someone else host and tell if it works better

**Comment by Zakaria-ouertani** [comment]
It did work better (very late)
