### ISSUE TITLE
Is it possible to use TCP instead of UDP in the server/client?

### ISSUE THREAD

**Issue by lesserfish** [TES3MP/openmw-tes3mp#688]
Hello! I am trying to run this on a custom server that I like to use.

Unfortunately, my server allows only TCP inbound packets, and not UDP. Is there a way to force the server / client to connect via TCP instead of UDP?

Thank you very much!

**Comment by testman42** [comment]
As far as I am aware, no.
Can you tell us what exactly is your setup. How come your server is unable to accept UDP packets?
Also, what is your desired goal? Public server or playing with just a friend / specific group of people?

**Comment by lesserfish** [comment]
Hello. Thank you for the reply!

My setup is kind of weird.I pay for a Minecraft server that allows uploading custom server.jar files, I guess to allow people to run custom/modded servers. This .jar file runs in a OpenJDK docker image. Since the base image behind the OpenJDK docker image is Linux based, I uploaded the TES3MP server alongside my minecraft files, then created a simple java applications that started the TES3MP server and used it as the server.jar. It's a complete hack.

It worked for several weeks, but apparently the Minecraft server host has started blocking UDP packets in some regions.

I've called them and was migrated to another server that allowed UDP packets, so I'm thankfully able to host TES3MP again. However, I still feel like it could be interesting to allow the user to switch between TCP and UDP.

Should I close this issue?

**Comment by davidcernat** [comment]
TES3MP's networking library (based on RakNet) only uses UDP packets, so it's not really viable to somehow switch to TCP packets.

**Comment by lesserfish** [comment]
> TES3MP's networking library (based on RakNet) only uses UDP packets, so it's not really viable to somehow switch to TCP packets.

I see! Guess it's a no go then. 

As of now, my server still works. If UDP packets are dropped again I'll try to come up with a new hack or something.

Thanks for the reply. I'll close this.
